---
- name: Example Web Server Ansible Playbook (Nginx)
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Update
      command: apt update -y
    - name: Upgrade
      command: apt upgrade -y
    - name: Install Nginx
      command: apt install nginx -y
    - name: Start Nginx Service
      service:
        name: nginx
        state: started