---
- name: Example Web Server Ansible Playbook (Nginx)
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Update
      command: apt update -y
    - name: Upgrade
      command: apt upgrade -y
    - name: Install Nginx
      command: apt install nginx -y
    - name: Start Nginx Service
      service:
        name: nginx
        state: started
    - name: Delete The Default Nginx Web Page
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent
    - name: Create New Web Page
      copy:
        content: |
          <html>
          <head>
            <title>Personal Site</title>
          </head>
          <body>
          <p>This is a custom site.</p>
          </body>
        dest: /var/www/html/index.nginx-debian.html